// content.js - PART ONE's library: the docs, the tested examples and the glossary, read from content/docs.json.
//
// <claudes_code_comments>
// ** Function List **
// loadContent(file)              - the parsed content/docs.json (cached); throws a plain message if it is missing
// findDoc(content, key)          - a doc by uri, by file name or by a word of its title
// glossaryMarkdown(entries)      - glossary entries as markdown, grouped by kind, each with its source path
// lookupTerm(content, topic)     - glossary entries for a topic: exact term or alias first, then the term
//                                  containing the topic, then definitions mentioning it (capped)
// findExample(content, name)     - one tested example by name
// explainError(content, message) - the error tables and the .err examples that match an error message
//
// ** Technical Review **
// - Everything here is read-only and needs no install: a person can ask what a word means before SETTLE is on
//   their machine. content/docs.json is generated by tools/build-content.mjs from the repo's own docs, and a
//   test fails when it is stale.
// - explainError strips the "settle: line N:" prefix, then matches the message against every `| \`message\` |
//   cause |` row in the docs, treating <placeholders> in the documented message as wildcards. It also scans the
//   tested .err examples, so the answer can show a real program that produces the same error.
// </claudes_code_comments>

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const CONTENT_FILE = path.resolve(HERE, '..', 'content', 'docs.json');

let cache = null;
export function loadContent(file = CONTENT_FILE) {
  if (cache && cache.file === file) return cache.content;
  if (!fs.existsSync(file)) throw new Error(`settle-mcp: ${file} is missing; run \`npm run build\` in the settle-mcp folder`);
  const content = JSON.parse(fs.readFileSync(file, 'utf8'));
  cache = { file, content };
  return content;
}

export function findDoc(content, key) {
  if (!key) return null;
  const k = String(key).toLowerCase();
  return (
    content.docs.find((d) => d.uri.toLowerCase() === k) ||
    content.docs.find((d) => d.name.toLowerCase() === k || d.name.toLowerCase() === `${k}.md`) ||
    content.docs.find((d) => d.name.toLowerCase().replace(/\.md$/, '').endsWith(k)) ||
    content.docs.find((d) => d.title.toLowerCase().includes(k)) ||
    null
  );
}

export function glossaryMarkdown(entries) {
  const kinds = [...new Set(entries.map((e) => e.kind))];
  const out = [];
  for (const kind of kinds) {
    out.push(`## ${kind}`, '');
    for (const e of entries.filter((x) => x.kind === kind)) {
      const alias = e.aliases?.length ? ` (was: ${e.aliases.join(', ')})` : '';
      const fam = e.family ? ` [${e.family}${e.block ? `, ${e.block}` : ''}]` : '';
      out.push(`- **${e.term}**${alias}${fam}: ${e.definition}  _(${e.source})_`);
    }
    out.push('');
  }
  return out.join('\n');
}

export function lookupTerm(content, topic, extra = []) {
  const all = [...content.glossary, ...extra];
  const t = String(topic).trim().toLowerCase().replace(/^:/, '');
  const exact = all.filter((e) => e.term.toLowerCase() === t || (e.aliases || []).some((a) => a.toLowerCase() === t));
  if (exact.length) return exact;
  const inTerm = all.filter((e) => e.term.toLowerCase().includes(t) || (e.aliases || []).some((a) => a.toLowerCase().includes(t)));
  if (inTerm.length) return inTerm.slice(0, 20);
  return all.filter((e) => e.definition.toLowerCase().includes(t)).slice(0, 12);
}

export function findExample(content, name) {
  const n = String(name).replace(/\.settle$/, '');
  return content.examples.find((e) => e.name === n) || null;
}

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

export function documentedErrors(content) {
  const rows = [];
  for (const d of content.docs) {
    for (const line of d.text.split('\n')) {
      const m = line.match(/^\|\s*`([^`]+)`\s*\|\s*(.+?)\s*\|\s*$/);
      if (!m || /^\|\s*`?(Message|Argument|Token)/i.test(line)) continue;
      if (!/[a-z]/.test(m[1]) || m[1].length < 6) continue;
      rows.push({ message: m[1], cause: m[2].replace(/`/g, ''), doc: d.path });
    }
  }
  return rows;
}

export function explainError(content, message) {
  const raw = String(message).trim();
  const line = (raw.match(/line (\d+):/) || [])[1];
  const core = raw.replace(/^settle:\s*/, '').replace(/^line \d+:\s*/, '').trim();
  const matches = [];
  for (const row of documentedErrors(content)) {
    const pattern = new RegExp('^' + row.message.split(/<[^>]+>/).map(escapeRe).join('.+?') + '$', 'i');
    const loose = row.message.replace(/<[^>]+>/g, '').trim().toLowerCase();
    if (pattern.test(core) || (loose.length > 12 && core.toLowerCase().includes(loose))) matches.push(row);
  }
  const examples = content.examples.filter((e) => e.err && e.err.includes(core.slice(0, 60))).slice(0, 3);
  return { line: line ? Number(line) : null, message: core, matches: matches.slice(0, 6), examples };
}
