// content.js - PART ONE's library: the docs, the tested examples and the glossary, read from content/docs.json.
//
// <claudes_code_comments>
// ** Function List **
// loadContent(file)              - the parsed content/docs.json (cached); throws a plain message if it is missing
// findDoc(content, key)          - a doc by uri, by file name or by a word of its title
// glossaryMarkdown(entries)      - glossary entries as markdown, grouped by kind, each with its source path
// lookupTerm(content, topic)     - glossary entries for a topic: exact term or alias first, then the term
//                                  containing the topic, then definitions mentioning it (capped)
// findExample(content, name)     - one tested example by name
// documentedErrors(content)     - every documented error row (single or double backticks) with its cause and doc
// parseErrorText(message)       - an error as printed: the message, its line, the caret's column and the marked text,
//                                  the suggestion (did you mean ...), whether settle or kanerva printed it
// explainError(content, message) - the error tables and the .err examples that match an error message
//
// ** Technical Review **
// - Everything here is read-only and needs no install: a person can ask what a word means before SETTLE is on
//   their machine. content/docs.json is generated by tools/build-content.mjs from the repo's own docs, and a
//   test fails when it is stale.
// - explainError reads the whole printed error (parseErrorText): the first line, the excerpt and the caret line the
//   settle and kanerva commands add, and a "did you mean" suggestion. It strips the "settle: line N:" prefix, then matches the message against every `| \`message\` |
//   cause |` row in the docs, treating <placeholders> in the documented message as wildcards. It also scans the
//   tested .err examples, so the answer can show a real program that produces the same error.
// </claudes_code_comments>

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const CONTENT_FILE = path.resolve(HERE, '..', 'content', 'docs.json');

let cache = null;
export function loadContent(file = CONTENT_FILE) {
  if (cache && cache.file === file) return cache.content;
  if (!fs.existsSync(file)) throw new Error(`settle-mcp: ${file} is missing; run \`npm run build\` in the settle-mcp folder`);
  const content = JSON.parse(fs.readFileSync(file, 'utf8'));
  cache = { file, content };
  return content;
}

export function findDoc(content, key) {
  if (!key) return null;
  const k = String(key).toLowerCase();
  return (
    content.docs.find((d) => d.uri.toLowerCase() === k) ||
    content.docs.find((d) => d.name.toLowerCase() === k || d.name.toLowerCase() === `${k}.md`) ||
    content.docs.find((d) => d.name.toLowerCase().replace(/\.md$/, '').endsWith(k)) ||
    content.docs.find((d) => d.title.toLowerCase().includes(k)) ||
    null
  );
}

export function glossaryMarkdown(entries) {
  const kinds = [...new Set(entries.map((e) => e.kind))];
  const out = [];
  for (const kind of kinds) {
    out.push(`## ${kind}`, '');
    for (const e of entries.filter((x) => x.kind === kind)) {
      const alias = e.aliases?.length ? ` (was: ${e.aliases.join(', ')})` : '';
      const fam = e.family ? ` [${e.family}${e.block ? `, ${e.block}` : ''}]` : '';
      out.push(`- **${e.term}**${alias}${fam}: ${e.definition}  _(${e.source})_`);
    }
    out.push('');
  }
  return out.join('\n');
}

export function lookupTerm(content, topic, extra = []) {
  const all = [...content.glossary, ...extra];
  const t = String(topic).trim().toLowerCase().replace(/^:/, '');
  const exact = all.filter((e) => e.term.toLowerCase() === t || (e.aliases || []).some((a) => a.toLowerCase() === t));
  if (exact.length) return exact;
  const inTerm = all.filter((e) => e.term.toLowerCase().includes(t) || (e.aliases || []).some((a) => a.toLowerCase().includes(t)));
  if (inTerm.length) return inTerm.slice(0, 20);
  return all.filter((e) => e.definition.toLowerCase().includes(t)).slice(0, 12);
}

export function findExample(content, name) {
  const n = String(name).replace(/\.settle$/, '');
  return content.examples.find((e) => e.name === n) || null;
}

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// a documented error row: | `message` | cause | or | `` message with `code` in it `` | cause |
const ROW = /^\|\s*(`+)\s*(.+?)\s*\1\s*\|\s*(.+?)\s*\|\s*$/;
export function documentedErrors(content) {
  const rows = [];
  for (const d of content.docs) {
    for (const line of d.text.split('\n')) {
      const m = line.match(ROW);
      if (!m || /^\|\s*`*\s*(Message|Argument|Token)/i.test(line)) continue;
      if (!/[a-z]/.test(m[2]) || m[2].length < 6) continue;
      rows.push({ message: m[2], cause: m[3].replace(/``\s*(.+?)\s*``/g, '"$1"').replace(/`/g, ''), doc: d.path });
    }
  }
  return rows;
}

// what settle (or kanerva) printed for an error: the first line `settle: line N: <message>`, then, from the command,
// the program line with a caret under the place and its column (settle-rs docs/06-errors.md, "How an error is reported")
export function parseErrorText(message) {
  const lines = String(message).replace(/\r/g, '').split('\n');
  const at = lines.findIndex((l) => /^\s*(settle|kanerva):\s/.test(l));
  const head = (at >= 0 ? lines[at] : lines.find((l) => l.trim()) || '').trim();
  const program = (head.match(/^(settle|kanerva):/) || [])[1] || null;
  const line = (head.match(/^(?:settle|kanerva):\s*line (\d+):/) || [])[1];
  const core = head.replace(/^(settle|kanerva):\s*/, '').replace(/^line \d+:\s*/, '').trim();
  let excerpt = null;
  let column = null;
  let underline = null;
  for (const l of lines) {
    const src = l.match(/^\s*(\d+) \| (.*)$/);
    if (src) excerpt = { line: Number(src[1]), text: src[2] };
    const car = l.match(/^\s*\|\s*?( *)(\^+)\s*column (\d+)\s*$/);
    if (car) {
      column = Number(car[3]);
      underline = car[2].length;
    }
  }
  const sugg = core.match(/did you mean (`[^`]+`|:[A-Za-z_][\w-]*)\?/i);
  const rest = lines.slice(at >= 0 ? at + 1 : 1).filter((l) => l.trim() && !/^\s*\d+ \| /.test(l) && !/^\s*\|/.test(l));
  return {
    program,
    line: line ? Number(line) : null,
    message: core,
    column,
    marked: excerpt && column ? excerpt.text.slice(column - 1, column - 1 + (underline || 1)) : null,
    excerpt,
    suggestion: sugg ? sugg[1].replace(/`/g, '') : null,
    more: rest,
  };
}

export function explainError(content, message) {
  const p = parseErrorText(message);
  const core = p.message;
  const matches = [];
  for (const row of documentedErrors(content)) {
    const pattern = new RegExp('^' + row.message.split(/<[^>]+>/).map(escapeRe).join('.+?') + '$', 'i');
    const loose = row.message.replace(/<[^>]+>/g, '').trim().toLowerCase();
    if (pattern.test(core) || (loose.length > 12 && core.toLowerCase().includes(loose))) matches.push(row);
  }
  const examples = content.examples.filter((e) => e.err && e.err.includes(core.slice(0, 60))).slice(0, 3);
  return { ...p, matches: matches.slice(0, 6), examples };
}
